### PR TITLE
Multisite Guide

### PR DESCRIPTION
**Pull request by jwbowers**
Just opening a pull request so that we can see what needs comments. Assigning three of us here with @amwilk as first mover, perhaps.

### CODE REVIEW

**Comment by amwilk** [comment]
Hi @jwbowers. I had already sent comments on this guide to you and Matt a while ago via email. Is this a new version that comes after the one I already reviewed? Thanks!

**Comment by jwbowers** [comment]
@amwilk  Thanks much. Sorry to have forgotten that. Not used to receiving reviews by email. Removing you from the commenting assignments.

**Comment by jwbowers** [comment]
@malisi Over to you for comments and edits.

**Comment by jwbowers** [comment]
@kristenbhunter You can see the PR information here. For now we are working in the multisite branch.

**Pull request merged**
