### PR TITLE
Main french translation

### PR DESCRIPTION
**Pull request by alyssaheinze**

### CODE REVIEW

**Comment by alyssaheinze** [comment]
@jwbowers 

I think we won't be able to merge this pull request on egap:main-french
because egap:main-french has commits that are more recent than when I branched off egap:main to start translating into French.

1 - If you give me access to egap/method-guides, I think I will be able to push my branch to your repo like this :
git push upstream main-french-translation 

2 - Otherwise, it would be nice of you if you could delete the branch egap:main-french and recreate it using the following command :
git checkout -b main-french 95d5787802075132b33c22e05148af960bfa17ff

where 95d5787802075132b33c22e05148af960bfa17ff is the commit id where I started the translation from.

I am not 100% sure of what I wrote.
So tell me if you think I am wrong.

**Comment by alyssaheinze** [comment]
@jwbowers 
Thank you!

**Comment by jwbowers** [comment]
Hi @alyssaheinze , I think this is now done.

**Comment by jwbowers** [comment]
Great work! So impressive!

**Comment by alyssaheinze** [comment]
Hi @jwbowers 

I think something weird happened during the merge.
I see some `<<<<<<< HEAD` in the code here for example : 
https://github.com/egap/methods-guides/blob/main-french/causal-inference/causal-inference.Rmd

I created a new pull request pointing to a new branch called egap:main-french-translation
https://github.com/egap/methods-guides/pull/47

But this branch does not contain the changes you made after.

Thank you!

**Pull request merged**
