### PR TITLE
Wilke causal inference edits

### PR DESCRIPTION
**Pull request by amwilk**
@jwbowers @malisi This branch contains my updates to the guide called "10 Things to Know About Causal Inference." These are my main changes:

- I re-ordered the 10 points in a way that I find more intuitive. The guide now moves roughly from points that related to what a causal effect is to how we learn about causal effects. 
- I updated the language - in some parts in minor ways and in some parts more substantially. Often, this involved adding more detail, e.g., to make examples easier to understand. 

The updates are probably substantial enough for you to take a look whether you like them. 

There is one part where I am not sure (@malisi I also made a comment about that in our google doc). In the first paragraph, in the old version it says "Under this approach there is no notion that just because X caused Y that X is the main reason or the only reason why Y happened." It is unclear which approach "this approach" refers to. I changed it to "Under the "production" approach" but am not sure that this is correct. The paragraph on "Causes are non-rival." seems to suggest that the same goes for the counterfactual approach to causality. From briefly reading up on the production approach, it seems to me though that the statement fits here too. Let me know whether you have thoughts - or I can reach out to Macartan and ask him what he meant there.

### CODE REVIEW

**Comment by macartan** [comment]
@anna that claim is about the counterfactual approach.

**Comment by amwilk** [comment]
@macartan Great! That solves that problem - thanks for letting me know. Also, since this is your guide, if you would like to look at my changes and/or don't like any of them, I am of course happy to revert.

**Comment by jwbowers** [comment]
@amwilk I bet that @macartan can make line by line comments and even edits on your pull request. I'll go through this more carefully this weekend: grades are due Friday.

**Comment by jwbowers** [comment]
Hey @amwilk, I'm merging this now. Looks great. I added only a few things. Feel free to check them out and we can easily edit further or revert if needed. Jake

**Comment by amwilk** [comment]
Thanks @jwbowers - this looks great!

**Pull request merged**
